services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8443:443"
    env_file:
      - ".env"
    restart: unless-stopped