# services:
#   nginx:
#     build:
#       context: ./requirements/nginx
#       dockerfile: Dockerfile
#     container_name: nginx
#     ports:
#       - "8443:443"
#     env_file:
#       - ".env"
#     restart: unless-stopped

# docker-compose.yml

# services:
#   mariadb:
#     build: 
#       context: ./requirements/mariadb
#     container_name: mariadb
#     image: mariadb
#     restart: always
#     env_file:
#       - .env
#     networks:
#       - inception_network
#     volumes:
#       - mariadb_data:/var/lib/mysql

# volumes:
#   mariadb_data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/arajma/data/mariadb

# networks:
#   inception_network:
#     driver: bridge
services:
  mariadb:
      image: mariadb
      build: requirements/mariadb/.
      container_name: mariadb
      restart: always
      env_file:
        - .env
      volumes:
        - mariadb_data:/var/lib/mysql
      secrets:
        - mysql_root_password
        - mysql_password
      networks:
        inception:

networks:
  inception:
    name: inception

secrets:
  mysql_root_password:
    file: ../secrets/mysql_root_password.txt
  mysql_password:
    file: ../secrets/mysql_password.txt

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /goinfre/arajma/data/mariadb